# Generated by Django 5.0.1 on 2024-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='C1',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='closeLoad1',
            new_name='motor1',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='closeLoad2',
            new_name='motor2',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='C2',
            new_name='pwm1',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='R1',
            new_name='pwm2',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='R2',
            new_name='rpm1',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='decLoad1',
            new_name='rpm2',
        ),
        migrations.RenameField(
            model_name='anomalypackets',
            old_name='decLoad2',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='anomalypackets',
            name='incLoad1',
        ),
        migrations.RemoveField(
            model_name='anomalypackets',
            name='incLoad2',
        ),
        migrations.AddField(
            model_name='anomalypackets',
            name='voltage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
