# Generated by Django 5.0.1 on 2024-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_user_approved',
            field=models.BooleanField(default=False),
        ),
    ]
