# Generated by Django 5.0.1 on 2024-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_networktraffic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktraffic',
            name='is_anomaly',
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='anomaly_packets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='normal_packets',
            field=models.IntegerField(default=0),
        ),
    ]
