# Generated by Django 5.0.1 on 2024-03-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_networktraffic_is_anomaly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tcp_count', models.IntegerField(default=0)),
                ('udp_count', models.IntegerField(default=0)),
                ('modbus_count', models.IntegerField(default=0)),
                ('mqtt_count', models.IntegerField(default=0)),
                ('others_count', models.IntegerField(default=0)),
            ],
        ),
    ]
