# Generated by Django 5.0.1 on 2024-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_protocolcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('normal_packets', models.IntegerField(default=0)),
                ('security_packets', models.IntegerField(default=0)),
            ],
        ),
    ]
