# Generated by Django 5.0.1 on 2024-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_securitytraffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_size', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('num_pkts_src', models.IntegerField()),
                ('num_pkts_dst', models.IntegerField()),
                ('modbus_function_code', models.IntegerField()),
                ('R1', models.IntegerField()),
                ('R2', models.IntegerField()),
                ('C1', models.IntegerField()),
                ('C2', models.IntegerField()),
                ('incLoad1', models.BooleanField()),
                ('decLoad1', models.IntegerField()),
                ('incLoad2', models.BooleanField()),
                ('decLoad2', models.IntegerField()),
                ('closeLoad1', models.BooleanField()),
                ('closeLoad2', models.BooleanField()),
            ],
        ),
    ]
