# Generated by Django 5.0.1 on 2024-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_anomalypackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalypackets',
            name='dst_ip',
            field=models.CharField(default='1.1.1.1', max_length=30),
        ),
        migrations.AddField(
            model_name='anomalypackets',
            name='dst_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomalypackets',
            name='src_ip',
            field=models.CharField(default='1.1.1.1', max_length=30),
        ),
        migrations.AddField(
            model_name='anomalypackets',
            name='src_port',
            field=models.IntegerField(default=0),
        ),
    ]
