# Generated by Django 5.0.1 on 2024-03-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_anomalypackets_dst_ip_anomalypackets_dst_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(default='1.1.1.1', max_length=30)),
                ('dst_ip', models.CharField(default='1.1.1.1', max_length=30)),
                ('src_port', models.IntegerField(default=0)),
                ('dst_port', models.IntegerField(default=0)),
                ('payload_size', models.IntegerField()),
                ('window_size', models.IntegerField()),
                ('num_pkts_src', models.IntegerField()),
                ('num_pkts_dst', models.IntegerField()),
                ('modbus_function_code', models.IntegerField()),
                ('ttl_value', models.IntegerField()),
            ],
        ),
    ]
